version: "3.7"
services:
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc

  doodleback:
    build : ./api/
    container_name: doodleback
    depends_on:
      - db
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
  
  doodlefront: 
    build: 
      context: ./front/
      dockerfile: Dockerfile
      target : prod
    container_name: doodlefront
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./server-confs:/server-confs
      #- ./certificates:/etc/letsencrypt
    environment:
      - SERVER_NAME=ahammad.diverse-team.fr pad.ahammad.diverse-team.fr myadmin.ahammad.diverse-team.fr
      - SERVE_FILES=yes
      - DISABLE_DEFAULT_SERVER=no
      - PROXY_REAL_IP=yes
      - USE_LIMIT_REQ=no
      - AUTO_LETS_ENCRYPT=no
      - REDIRECT_HTTP_TO_HTTPS=no
      - HTTP2=no
      - FEATURE_POLICY=accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'self'; usb 'none'; vibrate 'none'; vr 'none'

  etherpad:
    image: etherpad/etherpad:stable
    container_name: etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  
  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always
    ports:
      - "2525:25"

  myadmin:
    image: phpmyadmin
    container_name: myadmin
    ports:
      - "8082:80"
    environment:
      - PMA_ABSOLUTE_URI=http://myadmin.ahammad.diverse-team.fr
